Fix CI false positive result

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -49,6 +49,7 @@ jobs:
 
       - name: Run simulation
         run: |
+          set -e  # exit whenever something fails
           export AUDIODEV=null
           export LIBGL_ALWAYS_SOFTWARE=true
           export DEBIAN_FRONTEND=noninteractive
